### PR TITLE
Different layout for Research sub page

### PR DESCRIPTION
**Pull request by UlrikeHeine**
I made quite a few changes with the help of my brother-in-law, who is a developer. I hope I didn't mess it up too much ;0
Let me know how it comes out.

### CODE REVIEW

**Comment by hpillar** [comment]
Hi all, 
I checked and couldn't get the RESEARCH page to build nicely on my end. I hoped to accept the team & girl day changes in isolation (with git cherry-pick on the command line) then read this is not advised because I would be duplicating Ulrike's commit...
Sorry I don't know how to proceed from here - Tim & Nora any advice?
Thanks,
Helen

**Comment by UlrikeHeine** [comment]
Hello Helen,

I rebuilt the Research page yesterday; sorry, I should have sent you a
note! I also made changes to the team and outreach page, which were
automatically added to the same request. I think we have to wait until Tim
has time to review my pull request.

All best, Ulrike

**Comment by hpillar** [comment]
Hi Ulrike,
Yes let's wait for the pros! 
Have a great weekend,
Helen

**Comment by timothyas** [comment]
Hey all, sorry for the delay - the move was crazy hectic! But we are finally reaching some level of normal... 

I also had trouble building this locally, and found that it was a typo in _data/sitetext.yml . The issue was a relatively simply typo: the number of spaces before `- name: Ulrike Heine` and the lines below that have to match what is above exactly, and they were just off by one. 

I'll go ahead and merge this after fixing this so everyone can see the new layout, and @UlrikeHeine you may want to make your picture square since it's a little bit distorted.

**Comment by hpillar** [comment]
Nice Tim - sorry I didn't spot this. Hope you're enjoying settling in to your new pad :  )

**Comment by timothyas** [comment]
No problem @hpillar! I wouldn't have noticed it, but bundle told me to add the `--trace` option to `bundle exec jekyll serve` and it pretty much told me the bug in the first line of output. Just passing that on in case it helps in the future.

And thanks, we're digging it :)

**Comment by UlrikeHeine** [comment]
Hello Tim, 

Thanks so much for putting this draft of the research page up! The design as I had envisioned for the research page needs more work; I will get on it and send through a new pull request.

Hope you had a good start in Colorado! 

All best,
Ulrike

**Pull request merged**
