### PR TITLE
fig for amoc section

### PR DESCRIPTION
**Pull request by hpillar**

### CODE REVIEW

**Comment by NoraLoose** [comment]
Hi Helen! Ah, here is the .png, perfect! Next time, can you include the figure and changes of the .md file in one single pull request? Thanks! (If I was more experienced at reviewing pull requests, I wouldn't have let the first one with out the .png passed. ;)).

**Comment by hpillar** [comment]
Yes sure - I only sent 2 request because I forgot the figure the first time ;) Thanks for managing all this : )

I don’t want to create more work for you guys (because this still needs to be edited), but do you want me to submit a pull request for these changes shown in the screenshot now? 
Might aid quick adds from other people and give initial impression of whether to merge suggested topics.

My changes:

(1) added a bunch of square png to the assets/img/research/
(2) created the _research/*.md files
(3) made a tiny change to _includes/research_grid.html for the grey boxes with the research title  

H

**Comment by NoraLoose** [comment]
Sure, go ahead and create a pull request for those changes. (Do you mean the screenshot on Slack?) 
Thanks for getting in on the website development - this is great! :)

**Comment by hpillar** [comment]
Cool - I’m super slow, but I’m learning and it’s fun! : ) I attached a screenshot in the return mail too, but maybe that doesn’t work…
ok here it comes…

**Pull request merged**
