### PR TITLE
adding placeholders for research & tweaking layout

### PR DESCRIPTION
**Pull request by hpillar**
for now, project subtitle is not visible on RESEARCH landing page. Will try to edit so it shows when mouse hovers over button.
- Date: June 2020

### CODE REVIEW

**Comment by hpillar** [comment]
sorry, just saw I hadn't merged Tim's edit to sort projects by date.

**Comment by hpillar** [comment]
Though..perhaps later we could sort by theme? e.g.,:

[state-estimation    ice-reconstruct           QND    ]
[     AMOC                   sea-level             IO interact]
[       ML                                                                     ]

 if we add prefix e.g., r1, r2, ...,rN to *.md so the loop adds projects in desired order? Not important now though

**Comment by NoraLoose** [comment]
Patrick (@heimbach), do you mind reviewing this pull request? I have problems with my bundler and building the website locally. Will try to get it to work, though...

**Comment by heimbach** [comment]
Yes, I can give it a try. With some luck, tonight.

**Comment by NoraLoose** [comment]
Great, thanks!

**Comment by heimbach** [comment]
I still haven't really figured out how to bring my branch up to date with the latest master.

Following the MITgcm recipe
% git checkout master
% git pull upstream master
% git push origin master
% git checkout «YOUR_NEWBRANCH_NAME»
% git merge master

didn't work - as last time.

Using Tim's suggestion,
% git pull --rebase 

creates conflicts.

Do you have to have a recipe on how to update a branch?
Or is this not how it's supposed to be done?

Thanks
p.

**Comment by NoraLoose** [comment]
Also added @hpillar to the admin team for reviewing of future pull requests. :)

**Comment by heimbach** [comment]
Hmm, this makes me realize, I don't know what I am supposed to do to "review a pull request".

On the website, I see this:
"adding placeholders for research & tweaking layout"

and I see I can click the box, then mark it as "closed"

Is that what it is?

p.

**Comment by NoraLoose** [comment]
Before closing the PR, it has to be
1) reviewed, i.e., checked that it won't break anything and actually achieves the desired changes. In the case of the CRIOS website, this can best be ensured by pulling the suggested changes to your local machine and testing whether the website builds locally
2) merged, if everything is okay; otherwise: respond to the person who created the PR and ask for corrections.

Tim is updating the README right now to explain step 1) further.

**Comment by NoraLoose** [comment]
In 2., instead of asking for corrections, the reviewer can also make the corrections him/herself (and add further changes).

**Comment by heimbach** [comment]
I think I did that. Since I wasn't able to update my existing local copy I removed everything and cloned a new version checked out in cvs lingo), reinstalled bundle, and served it on my local disc.

It seemed to build fine, did it not?

p.

**Comment by NoraLoose** [comment]
Ah, perfect! (I have issues with the bundler on my local machine, so can't see if it builds.) So 1) seems to be done. Then you can go ahead and click "Merge pull request" (step 2))

**Comment by timothyas** [comment]
Don't merge it just yet!

**Comment by heimbach** [comment]
Good for you, I don't find where to click the "Merge pull request" button... :)

**Comment by timothyas** [comment]
Sorry, I've noticed a couple of conflicts that need to be addressed before this gets merged, explanation coming.

Thanks @heimbach and @NoraLoose for jumping in :) I am writing up some tips on merging pull requests that should be helpful in the future, to be added to the README. I'm using some screenshots from this PR that will hopefully help out. 

@heimbach: sorry you're running into trouble with updating your master branch. I'm not having any of these so I'm not really sure. Perhaps we can address this somewhere else, but are you making updates to your master branch? If so this could be causing the conflicts.

**Comment by timothyas** [comment]
@hpillar this looks AWESOME!!! Thank you for adding this content. I like how the subtitles show up when you hover over images! And the "square images" make the grid very clean :) 

One small thing: would you be able to update this branch to the upstream master branch? There are a couple of changes not present (e.g. the sorting that goes on [here](https://github.com/crios-ut/crios-ut.github.io/blob/e7328ab5e3d7c935fa3c458bc94efaf29e72abc5/_includes/research_grid.html#L11-L12) ). My recommended commands are:

```
git checkout master
git pull --rebase upstream master
git push origin master
git checkout hpedits_crios_webpage
git rebase master
```

then we should be good to go. There should not be conflicts based on what I see in the file changes, but if you run into trouble I can help.

**Comment by heimbach** [comment]
Sorry about that!
The quick answer is the obvious one: I don't know what I was/am doing... ;)

**Comment by timothyas** [comment]
After this gets merged I'll add my updates to the README with PR tips. But I'll wait until after to mess with the commit history ;)

**Comment by timothyas** [comment]
> Sorry about that! The quick answer is the obvious one: I don't know what I was/am doing... ;)

No problem! Git is certainly a bumpy road.

**Comment by timothyas** [comment]
I'll just say that I think admins are able to do this "branch rebasing" that I'm asking @hpillar to do, but I'm not sure how and it seems to be a tough one to google

**Comment by hpillar** [comment]
Thanks for the instructions @timothyas . I'm confused about this too...I followed the instructions on MITgcm contrib page:

% git checkout master
% git pull upstream master
% git push origin master
% git checkout «YOUR_NEWBRANCH_NAME»
% git merge master

and it showed me up to date. This is how I missed your previous edit to sort projects by date...

**Comment by hpillar** [comment]
but I will follow your instructions now. Back in a mo

**Comment by hpillar** [comment]
hmmm...this returned "already up to date too":

**(base) Helens-MacBook-Pro:crios-ut.github.io Helen$ git checkout master**
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
**(base) Helens-MacBook-Pro:crios-ut.github.io Helen$ git pull --rebase upstream master**
giFrom https://github.com/crios-ut/crios-ut.github.io
 * branch            master     -> FETCH_HEAD
Already up to date.
Current branch master is up to date.
**(base) Helens-MacBook-Pro:crios-ut.github.io Helen$ git push origin master**
Everything up-to-date
**(base) Helens-MacBook-Pro:crios-ut.github.io Helen$ git checkout hpedits_crios_webpage**
Switched to branch 'hpedits_crios_webpage'
Your branch is up to date with 'origin/hpedits_crios_webpage'.
**(base) Helens-MacBook-Pro:crios-ut.github.io Helen$ git rebase master**
Current branch hpedits_crios_webpage is up to date.

**Comment by timothyas** [comment]
Hmm, well that is peculiar. I'm not totally sure what's up, but given that there's just one small change, I'll just go ahead and tweak that little line back

**Comment by NoraLoose** [comment]
Nice job, Helen! It looks really good. :) Also, thanks @timothyas for saving the show tonight. ("DON'T MERGE IT QUITE YET!") :D

**Comment by hpillar** [comment]
Thanks @timothyas. Sorry for the trouble...I'm still trying to figure it out. It's weird because it worked earlier today (e.g., I followed the lines I pasted to pull all the new team photos from upstream). 

But yes - @timothyas thanks for saving the show!!! And thanks @NoraLoose for adding me to admin...but after tonight...are you sure that's wise?! ;-)

**Comment by timothyas** [comment]
No problem! Isn't this a fun Friday night we're all having together? ;)

I hope you don't mind, I've modified the date of the projects to reorder things, basically just to bring ASTE and QND to the top row. This will be something @heimbach will want to weigh in on, but perhaps those details are for another day. For now, I think this is good to go

LGTM

**Comment by heimbach** [comment]
And to Patrick for TRYING to merge, but NOT KNOWING HOW TO DO IT fortunately... ;)

Seriously, thanks all for your hard work!!!

Perhaps we should do a hands-on tutorial to cover some basic procedures.
I feel it can't be that hard, if one know the steps...

**Pull request merged**
