### PR TITLE
Update research team

### PR DESCRIPTION
**Pull request by ArashBigdeli**

### CODE REVIEW

**Comment by timothyas** [comment]
Hey thanks for this @ArashBigdeli! Could you remove all of the changed files in this PR except for _data/sitetext.yml and your picture? e.g. the .idea/ folder, the .DS_STORE file

**Comment by timothyas** [comment]
Also, could you update your branch to reflect some of the recent changes in the master branch? e.g. while on your branch update_research_team

```
git remote add upstream git@github.com:crios-ut/crios-ut.github.io.git
git pull --rebase upstream master
git push
```

**Comment by timothyas** [comment]
Thanks Arash! Looks like there's just one file left: .idea/workspace.xml

What I plan to do is add .idea/* to the .gitignore file so this doesn't happen again. If I delete this file, would it mess things up for you? Just curious, I'm not familiar with it (I'm assuming it's from github desktop version)

**Comment by ArashBigdeli** [comment]
I think they come from a combination of pycharm IDE and its fancy
integration of git. I already added a bunch of them to gitignore, please do
the same for the remaining one.

**Comment by timothyas** [comment]
Ok I will just delete that last remaining file then.

**Pull request merged**
